import { index, integer, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { commercialRelationshipEnum, disputeKindEnum, disputeStatusEnum, listingStatusEnum, orderStatusEnum, pricingModelEnum, sellerStatusEnum, subjectTypeEnum } from "./enums";
import { organisations } from "./organisations";
import { users } from "./auth";

export const sellerProfiles = pgTable("seller_profiles", { id: uuid("id").primaryKey().defaultRandom(), organisationId: uuid("organisation_id").notNull().references(() => organisations.id, { onDelete: "cascade" }), legalEntityName: text("legal_entity_name").notNull(), countryCode: text("country_code").notNull(), taxIdentifier: text("tax_identifier"), status: sellerStatusEnum("status").notNull().default("pending"), verifiedAt: timestamp("verified_at", { withTimezone: true }), suspendedReason: text("suspended_reason"), createdByUserId: uuid("created_by_user_id").notNull().references(() => users.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("seller_profile_org_idx").on(t.organisationId)]);

export const listings = pgTable("listings", { id: uuid("id").primaryKey().defaultRandom(), sellerId: uuid("seller_id").notNull().references(() => sellerProfiles.id, { onDelete: "cascade" }), subjectType: subjectTypeEnum("subject_type").notNull(), subjectId: uuid("subject_id").notNull(), title: text("title").notNull(), description: text("description"), commercialRelationship: commercialRelationshipEnum("commercial_relationship").notNull(), disclosureSummary: text("disclosure_summary").notNull(), status: listingStatusEnum("status").notNull().default("draft"), publishedAt: timestamp("published_at", { withTimezone: true }), createdByUserId: uuid("created_by_user_id").notNull().references(() => users.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("listing_seller_subject_idx").on(t.sellerId, t.subjectType, t.subjectId), index("listing_status_idx").on(t.status, t.publishedAt)]);

export const offers = pgTable("offers", { id: uuid("id").primaryKey().defaultRandom(), listingId: uuid("listing_id").notNull().references(() => listings.id, { onDelete: "cascade" }), name: text("name").notNull(), pricingModel: pricingModelEnum("pricing_model").notNull(), priceMinorUnits: integer("price_minor_units").notNull().default(0), currency: text("currency").notNull().default("AUD"), billingPeriod: text("billing_period"), usageUnit: text("usage_unit"), regionCodes: text("region_codes").array().notNull().default([]), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [index("offer_listing_idx").on(t.listingId)]);

export const sponsoredPlacements = pgTable("sponsored_placements", { id: uuid("id").primaryKey().defaultRandom(), listingId: uuid("listing_id").notNull().references(() => listings.id, { onDelete: "cascade" }), slot: text("slot").notNull(), disclosureLabel: text("disclosure_label").notNull(), startsAt: timestamp("starts_at", { withTimezone: true }).notNull(), endsAt: timestamp("ends_at", { withTimezone: true }).notNull(), createdByUserId: uuid("created_by_user_id").notNull().references(() => users.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [index("sponsored_placement_window_idx").on(t.listingId, t.startsAt, t.endsAt)]);

export const marketplaceOrders = pgTable("marketplace_orders", { id: uuid("id").primaryKey().defaultRandom(), offerId: uuid("offer_id").notNull().references(() => offers.id), organisationId: uuid("organisation_id").notNull().references(() => organisations.id, { onDelete: "cascade" }), status: orderStatusEnum("status").notNull().default("pending"), amountMinorUnits: integer("amount_minor_units").notNull(), taxMinorUnits: integer("tax_minor_units").notNull(), totalMinorUnits: integer("total_minor_units").notNull(), currency: text("currency").notNull(), buyerCountryCode: text("buyer_country_code").notNull(), taxKind: text("tax_kind").notNull(), taxRateBasisPoints: integer("tax_rate_basis_points").notNull(), createdByUserId: uuid("created_by_user_id").notNull().references(() => users.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [index("order_org_status_idx").on(t.organisationId, t.status)]);

export const marketplaceDisputes = pgTable("marketplace_disputes", { id: uuid("id").primaryKey().defaultRandom(), listingId: uuid("listing_id").notNull().references(() => listings.id, { onDelete: "cascade" }), orderId: uuid("order_id").references(() => marketplaceOrders.id), raisedByUserId: uuid("raised_by_user_id").notNull().references(() => users.id), kind: disputeKindEnum("kind").notNull(), description: text("description").notNull(), status: disputeStatusEnum("status").notNull().default("open"), resolution: text("resolution"), resolvedByUserId: uuid("resolved_by_user_id").references(() => users.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), resolvedAt: timestamp("resolved_at", { withTimezone: true }) }, (t) => [index("dispute_listing_status_idx").on(t.listingId, t.status)]);
