import { boolean, index, jsonb, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { alertKindEnum, alertStatusEnum, mobilePlatformEnum, securitySeverityEnum, subjectTypeEnum } from "./enums";
import { users } from "./auth";

export const mobileDevices = pgTable("mobile_devices", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), platform: mobilePlatformEnum("platform").notNull(), deviceName: text("device_name"), pushToken: text("push_token").notNull(), pushEnabled: boolean("push_enabled").notNull().default(true), appVersion: text("app_version"), lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull().defaultNow(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("mobile_device_token_idx").on(t.userId, t.pushToken)]);

export const alertPreferences = pgTable("alert_preferences", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), subjectType: subjectTypeEnum("subject_type").notNull(), subjectId: uuid("subject_id").notNull(), scoreDrops: boolean("score_drops").notNull().default(true), newFindings: boolean("new_findings").notNull().default(true), verificationChanges: boolean("verification_changes").notNull().default(false), minSeverity: securitySeverityEnum("min_severity").notNull().default("high"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("alert_preference_subject_idx").on(t.userId, t.subjectType, t.subjectId)]);

export const mobileFavorites = pgTable("mobile_favorites", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), subjectType: subjectTypeEnum("subject_type").notNull(), subjectId: uuid("subject_id").notNull(), label: text("label"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("mobile_favorite_subject_idx").on(t.userId, t.subjectType, t.subjectId)]);

export const trustAlerts = pgTable("trust_alerts", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), subjectType: subjectTypeEnum("subject_type").notNull(), subjectId: uuid("subject_id").notNull(), kind: alertKindEnum("kind").notNull(), payload: jsonb("payload").$type<Record<string, unknown>>().notNull().default({}), status: alertStatusEnum("status").notNull().default("queued"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), sentAt: timestamp("sent_at", { withTimezone: true }) }, (t) => [index("trust_alert_user_status_idx").on(t.userId, t.status, t.createdAt)]);
