import { createHash } from "node:crypto";
import { and, eq } from "drizzle-orm";
import { v7 as uuidv7 } from "uuid";
import { auditEvents, auditExports, catalogueEntries, enterpriseCatalogues, policies, procurementDecisions, procurementRequests } from "@/db/schema";
import { db } from "@/lib/db/client";
import { z } from "zod";
const subject = z.object({ subjectType: z.enum(["company","product","mcp_server","skill","agent","model","api"]), subjectId: z.uuid() });
export const catalogueSchema=z.object({name:z.string().min(2).max(160),description:z.string().max(2000).optional()}); export const entrySchema=subject.extend({catalogueId:z.uuid(),internalNotes:z.string().max(4000).optional(),renewalAt:z.coerce.date().optional()}); export const requestSchema=subject.extend({catalogueEntryId:z.uuid().optional(),title:z.string().min(3).max(240),businessJustification:z.string().min(10).max(8000),riskSummary:z.string().max(8000).optional(),ownerUserId:z.uuid().optional()}); export const decisionSchema=z.object({decision:z.enum(["approve","reject","request_changes","grant_exception"]),rationale:z.string().min(10).max(8000),evidenceIds:z.array(z.uuid()).max(100).default([]),policyMappingIds:z.array(z.uuid()).max(100).default([]),exceptionExpiresAt:z.coerce.date().optional()}); export const policySchema=z.object({key:z.string().regex(/^[A-Z0-9_.-]{2,100}$/),title:z.string().min(3).max(240),version:z.string().min(1).max(80),bodyHash:z.string().regex(/^[a-f0-9]{64}$/),effectiveAt:z.coerce.date(),supersedesPolicyId:z.uuid().optional()});
export async function createCatalogue(input:unknown,a:{userId:string;organisationId:string}){const p=catalogueSchema.parse(input);const [r]=await db.insert(enterpriseCatalogues).values({id:uuidv7(),organisationId:a.organisationId,...p}).returning();return r}
export async function addCatalogueEntry(input:unknown,a:{userId:string;organisationId:string}){const p=entrySchema.parse(input);const [catalogue]=await db.select().from(enterpriseCatalogues).where(and(eq(enterpriseCatalogues.id,p.catalogueId),eq(enterpriseCatalogues.organisationId,a.organisationId))).limit(1);if(!catalogue)throw new Error("Catalogue not found");const [r]=await db.insert(catalogueEntries).values({id:uuidv7(),...p,createdByUserId:a.userId}).returning();return r}
export async function createRequest(input:unknown,a:{userId:string;organisationId:string}){const p=requestSchema.parse(input);const [r]=await db.insert(procurementRequests).values({id:uuidv7(),organisationId:a.organisationId,...p,requestedByUserId:a.userId,status:"submitted",submittedAt:new Date()}).returning();await db.insert(auditEvents).values({organisationId:a.organisationId,actorUserId:a.userId,action:"procurement.submitted",resourceType:"procurement_request",resourceId:r.id});return r}
export async function decideRequest(id:string,input:unknown,a:{userId:string;organisationId:string}){const p=decisionSchema.parse(input);return db.transaction(async tx=>{const [request]=await tx.select().from(procurementRequests).where(and(eq(procurementRequests.id,id),eq(procurementRequests.organisationId,a.organisationId))).limit(1);if(!request||!["submitted","assessing"].includes(request.status))throw new Error("Request is not ready for decision");const status=p.decision==="approve"||p.decision==="grant_exception"?"approved":p.decision==="reject"?"rejected":"assessing";const [decision]=await tx.insert(procurementDecisions).values({id:uuidv7(),requestId:id,...p,decidedByUserId:a.userId}).returning();await tx.update(procurementRequests).set({status,decidedAt:status==="assessing"?undefined:new Date(),updatedAt:new Date()}).where(eq(procurementRequests.id,id));if(request.catalogueEntryId&&p.decision==="grant_exception")await tx.update(catalogueEntries).set({exceptionExpiresAt:p.exceptionExpiresAt,status:"approved",updatedAt:new Date()}).where(eq(catalogueEntries.id,request.catalogueEntryId));await tx.insert(auditEvents).values({organisationId:a.organisationId,actorUserId:a.userId,action:"procurement.decided",resourceType:"procurement_request",resourceId:id,metadata:{decision:p.decision,evidenceIds:p.evidenceIds}});return decision})}
export async function createPolicy(input:unknown,a:{userId:string;organisationId:string}){const p=policySchema.parse(input);const [r]=await db.insert(policies).values({id:uuidv7(),organisationId:a.organisationId,...p,createdByUserId:a.userId}).returning();return r}
export async function createAuditExport(a:{userId:string;organisationId:string},scope:Record<string,unknown>={}){const material=JSON.stringify({organisationId:a.organisationId,scope,createdAt:new Date().toISOString()});const manifestHash=createHash("sha256").update(material).digest("hex");const signature=createHash("sha256").update(`${process.env.BETTER_AUTH_SECRET??"development"}:${manifestHash}`).digest("hex");const [r]=await db.insert(auditExports).values({id:uuidv7(),organisationId:a.organisationId,scope,manifestHash,signature,storageKey:`audit-exports/${a.organisationId}/${manifestHash}.json`,createdByUserId:a.userId}).returning();return r}
export async function listRequests(org:string){return db.select().from(procurementRequests).where(eq(procurementRequests.organisationId,org)).limit(200)}
